version: '3'

services:
  mongo:
    image: mongo:latest
  dev:
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "5000:5000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - PORT=5000
    depends_on:
      - mongo
    